name: MP_Windows

on:
  push:
    paths:
      - '.github/**'
      - 'mp/src/**'
  pull_request:
   paths:
      - 'mp/src/**'

jobs:
  build:
    runs-on:
      windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1

      - name: Create project
        working-directory: mp/src
        run: devtools/bin/vpc.exe /sdk2013ce /2013 +game /mksln sdk2013ce.sln

      - name: Build project
        working-directory: mp/src
        run: devenv sdk2013ce.sln /Build Release

      - name: Pack
        shell: bash
        run: tar cJfv Windows.tar.xz mp/game/mod_sdk2013ce/bin

      - name: Upload product
        uses: actions/upload-artifact@v4
        with:
          name: mp_sdk2013ce
          path: Windows.tar.xz
          if-no-files-found: error
